---
- name: Set up Kubernetes cluster via Kubeadm
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ./vars/default-vars.yml

  tasks:

    - name: Provision on GCP via Terraform
      ansible.builtin.include_role:
        name: manage_k8s_nodes_gcp
        tasks_from: provision_nodes.yml
      when: cloud_provider == "gcp"

    - name: Provision on AWS via Terraform
      ansible.builtin.include_role:
        name: manage_k8s_nodes_aws
        tasks_from: provision_nodes.yml
      when: cloud_provider == "aws_ec2"
