---
roles:
  - name: geerlingguy.docker
    version: 3.1.2
  - name: geerlingguy.pip
    version: 2.2.0
  - name: geerlingguy.kubernetes
    version: 7.1.2
  - name: geerlingguy.containerd
    version: 1.3.1
  - src: https://github.com/michaelford85/ansible-role-kubernetes.git

collections:
  - name: amazon.aws
    version: 5.2.0
  - name: community.aws
    version: 5.2.0
  - name: google.cloud
    version: 1.1.2
  - name: community.general
    version: 6.3.0
  - name: kubernetes.core
    version: 2.3.2
  - name: ansible.posix
    version: 1.5.1
