---
roles:
  - name: geerlingguy.docker
    version: 7.1.0
  - name: geerlingguy.pip
    version: 3.0.2
  - name: geerlingguy.kubernetes
    version: 8.0.0
  - name: geerlingguy.containerd
    version: 1.3.1
  - name: geerlingguy.docker
    version: 7.1.0
  # - src: https://github.com/michaelford85/ansible-role-kubernetes.git

collections:
  - name: amazon.aws
    version: 7.4.0
  - name: community.aws
    version: 7.1.0
  - name: google.cloud
    version: 1.3.0
  - name: community.general
    version: 8.4.0
  - name: kubernetes.core
    version: 3.0.1
  - name: ansible.posix
    version: 1.5.4
