---
- name: Teardown Kubeadm Kubernetes cluster
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ["./vars/custom-vars.yml", "./vars/default-vars.yml"]

  tasks:

    - name: Teardown GCP infrastructure via Terraform
      ansible.builtin.include_role:
        name: manage_k8s_nodes_gcp
        tasks_from: teardown_nodes.yml
      when: cloud_provider == "gcp"

    - name: Teardown AWS infrastructure via Terraform
      ansible.builtin.include_role:
        name: manage_k8s_nodes_aws
        tasks_from: teardown_nodes.yml
      when: cloud_provider == "aws_ec2"
