---
- name: Ensure AWS Terraform Directory Exists
  ansible.builtin.stat:
    path: /tmp/aws_deploy
  register: aws_deploy_directory

- name: Teardown AWS infrastructure via Terraform
  community.general.terraform:
    variables:
      access_key: "{{ aws_access_key }}"
      secret_key: "{{ aws_secret_key }}"
      ec2_region: "{{ ec2_region }}"
      ec2_prefix: "{{ cloud_prefix }}"
    project_path: /tmp/aws_deploy
    state: absent
  register: terraform_output
  when: aws_deploy_directory.stat.exists and aws_deploy_directory.stat.isdir
  no_log: true

# - name: Debug Terraform output
#   ansible.builtin.debug:
#     var: terraform_output
#   when: aws_deploy_directory.stat.exists and aws_deploy_directory.stat.isdir

- name: delete terraform directory
  ansible.builtin.file:
    path: /tmp/aws_deploy
    state: absent
  when: aws_deploy_directory.stat.exists and aws_deploy_directory.stat.isdir
