---
- name: Map instance_size shorthand to GCP machine type
  ansible.builtin.set_fact:
    gcp_machine_type: "{{ {'large': 'e2-standard-2', 'xlarge': 'e2-standard-4'}.get(instance_size, instance_size) }}"

- name: Copy GCP Terraform Directory
  ansible.builtin.copy:
    src: gcp_deploy
    dest: "{{ working_dir }}"
    mode: 0777

- name: Initialize Terraform
  ansible.builtin.command:
    cmd: terraform init
    chdir: "{{ working_dir }}/gcp_deploy"

- name: Provision on GCP via Terraform
  community.general.terraform:
    project_path: "{{ working_dir }}/gcp_deploy"
    state: present
    variables:
      gcp_project: "{{ gcp_project }}"
      gcp_region: "{{ gcp_region }}"
      gcp_zone: "{{ gcp_zone }}"
      gcp_prefix: "{{ cloud_prefix }}"
      gcp_instance_username: "{{ gcp_instance_username | default('ubuntu') }}"
      master_machine_type: "{{ gcp_machine_type }}"
      gcp_vpc_cidr: "{{ gcp_vpc_cidr | default('192.168.0.0/16') }}"
      gcp_subnet_cidr: "{{ gcp_vpc_subnet | default('192.168.0.0/20') }}"
      gcp_nodeport_cidr: "{{ gcp_nodeport_cidr | default('0.0.0.0/0') }}"
      num_instances: "{{ num_instances }}"
      gcp_disk_image: "{{ gcp_disk_image }}"
      machine_type: "{{ gcp_machine_type }}"
      cloud_master_volume_size: "{{ cloud_master_volume_size }}"
      cloud_worker_volume_size: "{{ cloud_worker_volume_size }}"
  register: terraform_output
