---
- name: Ensure GCP Terraform Directory Exists
  ansible.builtin.stat:
    path: "{{ working_dir }}/gcp_deploy"
  register: gcp_deploy_directory

- name: Teardown GCP infrastructure via Terraform
  community.general.terraform:
    project_path: "{{ working_dir }}/gcp_deploy"
    state: absent
    variables:
      gcp_key: "{{ gcp_local_credentials_file }}"
      gcp_project: "{{ gcp_project }}"
      gcp_region: "{{ gcp_region }}"
      gcp_zone: "{{ gcp_zone }}"
      gcp_prefix: "{{ cloud_prefix }}"
      gcp_instance_username: "{{ gcp_instance_username | default('ubuntu') }}"
      master_machine_type: "{{ instance_size | default('e2-standard-4') }}"
      gcp_vpc_cidr: "{{ gcp_vpc_cidr | default('192.168.0.0/16') }}"
      gcp_subnet_cidr: "{{ gcp_vpc_subnet | default('192.168.0.0/20') }}"
      gcp_nodeport_cidr: "{{ gcp_nodeport_cidr | default('0.0.0.0/0') }}"
      num_instances: "{{ num_instances }}"
      gcp_disk_image: "{{ gcp_disk_image }}"
      machine_type: "{{ instance_size | default('e2-standard-4') }}"
      cloud_master_volume_size: "{{ cloud_master_volume_size }}"
      cloud_worker_volume_size: "{{ cloud_worker_volume_size }}"
  register: terraform_output
  when: gcp_deploy_directory.stat.exists and gcp_deploy_directory.stat.isdir
  no_log: false

# - name: Debug Terraform output
#   ansible.builtin.debug:
#     var: terraform_output
#   when: gcp_deploy_directory.stat.exists and gcp_deploy_directory.stat.isdir

- name: Delete terraform directory
  ansible.builtin.file:
    path: "{{ working_dir }}/gcp_deploy"
    state: absent
  when: gcp_deploy_directory.stat.exists and gcp_deploy_directory.stat.isdir
